In [1]:
import numpy as np

# Creating Arrays

In [2]:
myList = [1, 2, 3, 4, 5, 6]
arr = np.array(myList)
arr #Vector

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.shape

(6,)

In [4]:
myMat = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(myMat)
arr2 #Matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.shape

(2, 4)

In [6]:
l1 = [[1, 2, 3], [4, 5, 6, 7]]
np.array(l1)

/var/folders/4y/pcdt74h51_x2zz4w3hlpvzxh0000gn/T/ipykernel_10586/2256753812.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(l1)


array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [7]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [9]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros((1000, 100))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full((2, 3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [13]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Reshaping Arrays

In [14]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr.reshape((5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr = arr.reshape(-1, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Array Indexing & Slicing

In [20]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr[1][1]

6

In [22]:
arr[:2, 2:]

array([[3, 4],
       [7, 8]])

# Sorting

In [23]:
arr = np.array([5, 44, 21, 347, 271])
arr

array([  5,  44,  21, 347, 271])

In [24]:
sorted(arr)

[5, 21, 44, 271, 347]

In [25]:
np.array(sorted(arr))

array([  5,  21,  44, 271, 347])

In [26]:
arr

array([  5,  44,  21, 347, 271])

In [27]:
arr.sort()

In [28]:
arr

array([  5,  21,  44, 271, 347])

# Fancy Indexing

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[[2, 0, 5, 7]]

array([2, 0, 5, 7])

# Broadcasting

In [34]:
l1 = list(range(1, 11))
a1 = np.array(l1)

In [35]:
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [36]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
l1[1:5] = 10

TypeError: can only assign an iterable

In [39]:
a1 * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
a1[1:5] = 100

In [41]:
a1

array([  1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

# Conditional Selection

In [42]:
a1 = np.array(l1)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [44]:
a1[a1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [45]:
a1%2==0 and a1%3==0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
(a1%2==0) & (a1%3==0)

array([False, False, False, False, False,  True, False, False, False,
       False])

In [48]:
a1[(a1%2==0) & (a1%3==0)]

array([6])

In [49]:
(a1%2==0) | (a1%3==0)

array([False,  True,  True,  True, False,  True, False,  True,  True,
        True])

In [50]:
a1[(a1%2==0) | (a1%3==0)]

array([ 2,  3,  4,  6,  8,  9, 10])